
# **Theoretical Questions:**


In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

NumPy is a Python library primarily used for efficient numerical computations, particularly with large datasets, by providing powerful multidimensional arrays and optimized mathematical functions, significantly enhancing Python's capabilities for scientific computing and data analysis by offering high performance, memory efficiency, and a concise syntax for complex operations compared to standard Python lists; making it a cornerstone for tasks like linear algebra, signal processing, and machine learning within the Python ecosystem.

**Key advantages of NumPy:**

* High Performance:
NumPy leverages optimized C libraries to perform calculations on arrays much faster than using standard Python loops, making it ideal for large-scale data processing.


**Memory Efficiency:**

* NumPy arrays store data in contiguous memory blocks, reducing memory overhead and improving access speed compared to Python lists.

* Multidimensional Arrays:
NumPy's core data structure, the "ndarray" (n-dimensional array), allows for efficient manipulation of data in multiple dimensions, crucial for tasks like matrix operations and image processing.

* Vectorized Operations:
NumPy enables performing operations on entire arrays element-wise, significantly reducing the need for explicit loops and improving code readability.

Extensive Mathematical Functions:
NumPy provides a comprehensive set of mathematical functions including trigonometric, linear algebra, statistical operations, and more, readily accessible for complex calculations.
Integration with other Libraries:
Many popular scientific computing libraries in Python, like SciPy and scikit-learn, are built on top of NumPy, allowing seamless integration and data exchange.

**Extensive Mathematical Functions:**

* NumPy provides a comprehensive set of mathematical functions including trigonometric, linear algebra, statistical operations, and more, readily accessible for complex calculations.

* Integration with other Libraries:
Many popular scientific computing libraries in Python, like SciPy and scikit-learn, are built on top of NumPy, allowing seamless integration and data exchange.


**How NumPy enhances Python for numerical operations:**

Simplified Syntax:

* NumPy provides a user-friendly syntax for performing complex mathematical operations on arrays, making code more concise and easier to read.

* Optimized for Large Datasets:
By leveraging compiled code, NumPy enables efficient processing of large datasets, which would be significantly slower with standard Python loops.

* Advanced Data Manipulation:
NumPy arrays can be easily sliced, indexed, and reshaped to access specific data subsets and perform transformations.


Example Use Cases:

* Data Analysis:
Calculating descriptive statistics like mean, standard deviation, or correlations across large datasets

* Scientific Simulations:
Solving differential equations or performing numerical integration in computational modeling

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

The main difference between the np.mean() and np.average() functions in NumPy is that np.average() allows you to consider the significance of numbers by using weights, while np.mean() is for a straightforward average of numbers:


**np.mean()**

Calculates the arithmetic mean of an array along a specific axis. The default is along the flattened axis.

**np.average()**

Calculates the weighted average along a specified axis. It takes an optional weight argument, which is not available in the np.mean() function.

"NumPy is an open-source Python library for scientific and mathematical computing. It contains a collection of high-level mathematical functions, including support for multi-dimensional arrays, masked arrays, and matrices".


onclusion

In numpy library, both np.mean() and np.average() can be used to calculate arithmetic mean. The differenece comes when we have to perform average on weighted array. np.average() gives us flexibilty to work with the weighted arrays too. If we pass the weight of the array to the function, it can perform weighted average at very ease. That is not the case for the np.mean(). It can only be perfomred on non-weighted arrays

In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

Reversing a NumPy array along different axes can be achieved using various methods. Here are detailed explanations and examples for both 1D and 2D arrays

1. Reversing a 1D

* a. Using Slicing

I can reverse a 1D array by using slicing with a step of -1.



* b. Using np.flip

The np.flip function can also reverse a 1D array.





In [1]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = arr_1d[::-1]
print(reversed_1d)


[5 4 3 2 1]


In [2]:
print(reversed_1d)

[5 4 3 2 1]


In [4]:
# Reverse using np.flip
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)

[5 4 3 2 1]


**2. Reversing a 2D Array**

* a. Reversing Rows:

I can reverse a 2D array along the first axis (rows) using slicing or np.flip.

In [ ]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse rows using slicing
reversed_rows = arr_2d[::-1]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Reverse rows using np.flip
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


* b. Reversing Columns:

To reverse a 2D array along the second axis (columns), use slicing or np.flip.



In [ ]:
# Reverse columns using slicing
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# Reverse columns using np.flip
reversed_columns_flip = np.flip(arr_2d, axis=1)
print(reversed_columns_flip)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


**Summary**

* 1D Arrays:  
Use slicing [::-1] or np.flip to reverse.

* 2D Arrays:
    * .Reverse rows: arr[::-1] or np.flip(arr, axis=0).
    * .Reverse columns: arr[:, ::-1] or np.flip(arr, axis=1).
    *.Reverse both axes: np.flip(arr).
    
These methods provide flexible options for reversing arrays in NumPy!





In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In NumPy, I can determine the data type of elements in an array using the .dtype attribute. Here’s how I can do it:



In [5]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4])

# Check the data type
data_type = array.dtype
print(data_type)  # Output: int64 (or int32 depending on your system)


int64


**Importance of Data Types**

1. emory Management:
Different data types require different amounts of memory. For instance, an int32 uses 4 bytes, while an int64 uses 8 bytes. By choosing the appropriate data type, I can significantly reduce memory usage, which is crucial when working with large datasets.

2. Performance:

Operations on arrays with smaller data types can be faster, as they require less bandwidth and processing power. For example, performing computations on float32 arrays is generally faster than on float64 arrays due to lower memory usage and reduced computational overhead.

3. Precision:

The choice of data type can also affect the precision of calculations. Using a float64 instead of float32 may be necessary for applications requiring higher precision, but this comes at the cost of increased memory usage.

4. Type Safety:

NumPy enforces a consistent data type across arrays, which helps prevent bugs and improves code clarity. It ensures that operations on arrays yield predictable results.


In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, ndarrays (N-dimensional arrays) are the core data structure that allows for efficient numerical computations. Here are their key features:

**Key Features of ndarrays:**
1. Homogeneous Data:

All elements in an ndarray must be of the same data type, which allows for more efficient storage and computation.

2. Multidimensional:

Ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), allowing for complex data structures such as matrices and tensors.

3. Contiguous Memory Allocation:

Ndarrays are stored in contiguous memory locations, which improves cache efficiency and speeds up operations compared to non-contiguous data structures.

4. Vectorized Operations:

Ndarrays support element-wise operations, which means you can perform operations on entire arrays without writing explicit loops. This leads to cleaner and faster code.

5. Broadcasting:

NumPy provides broadcasting, allowing operations between arrays of different shapes, automatically expanding the smaller array to match the shape of the larger one.

6. Rich Functionality:

Ndarrays come with a vast library of mathematical and statistical functions that can be applied directly, enabling complex operations with minimal code.



**Differences from Standard Python Lists:**

1. Data Type:

Python lists can contain mixed data types (e.g., integers, floats, strings), while ndarrays require all elements to be of the same type.

2. Performance:

Ndarrays are optimized for numerical operations and are generally faster than Python lists for large datasets due to their contiguous memory allocation and efficient algorithms.

3. Dimensionality:

Ndarrays can have multiple dimensions (e.g., matrices, tensors), while Python lists are inherently one-dimensional unless you create nested lists.

4. Functionality:

NumPy provides a wide array of mathematical functions and operations specifically designed for ndarrays, which are not available for standard lists. Operations like element-wise addition, multiplication, and linear algebra can be performed directly on ndarrays.

5. Memory Efficiency:

Ndarrays are more memory-efficient for large datasets since they use a fixed type for all elements, reducing overhead compared to Python lists, which can require additional memory for type information.


In summary, ndarrays are a powerful and efficient alternative to Python lists, particularly for numerical computations, due to their structured design and optimized performance.

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer significant performance benefits over standard Python lists, especially for large-scale numerical operations. Here’s an analysis of these benefits:

1. Speed of Computation:

    *  Vectorization: NumPy allows for vectorized operations, enabling element-wise computations without explicit loops. This leads to optimized execution in compiled code rather than interpreted Python code, making operations on large datasets much faster.

    * C-based Backend: NumPy is built on C and Fortran libraries, leveraging low-level optimizations. This reduces overhead and enhances performance for numerical operations compared to the slower Python list operations.

2. Memory Efficiency:

    * Contiguous Memory Storage: NumPy arrays are stored in contiguous blocks of memory, which improves cache coherence. This means that accessing consecutive elements is faster, as they are likely to be loaded into CPU cache.

    * Fixed Data Types: Ndarrays require elements to be of a uniform type, which allows for more compact storage. In contrast, Python lists can contain elements of different types, which adds overhead for type management and can lead to larger memory usage.

3. Reduced Overhead:

      * Lower Memory Footprint: NumPy uses less memory per element than Python lists because of its fixed-size data types and more efficient memory handling. For large datasets, this can lead to substantial savings.

      * Fewer Function Calls: Operations on NumPy arrays are often implemented as single calls to optimized functions, whereas Python lists may involve multiple function calls and Python-level loops, increasing execution time.

4. Advanced Features:

  * Broadcasting: NumPy’s broadcasting allows operations on arrays of different shapes without the need for manual replication of data. This feature simplifies code and improves performance by avoiding unnecessary memory usage.

  * Built-in Mathematical Functions: NumPy provides a wide range of optimized mathematical functions that can be applied directly to arrays, allowing for high-performance computations without the need for custom implementations.

5. Parallelism and Optimization:

 * Many NumPy operations can be optimized using parallel processing and low-level optimizations, further improving performance. For instance, certain NumPy functions can utilize multiple cores or hardware acceleration.
**Conclusion:**

For large-scale numerical operations, the performance benefits of using NumPy arrays over Python lists are clear. The combination of speed, memory efficiency, reduced overhead, and advanced features makes NumPy a preferred choice for numerical and scientific computing. These advantages become especially pronounced as the size and complexity of the data increase, enabling faster and more efficient data processing.






In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. Here’s a comparison of the two, along with examples demonstrating their usage.

**vstack()**

* Function: Stacks arrays vertically (row-wise).
* Usage: Combines arrays along the vertical axis (axis=0).

Example of vstack()


In [6]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)


Result of vstack:
[[1 2]
 [3 4]
 [5 6]]


**hstack()**

* Function: Stacks arrays horizontally (column-wise).
* Usage: Combines arrays along the horizontal axis (axis=1).

Example of hstack()

In [7]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)


Result of hstack:
[[1 2 5]
 [3 4 6]]


**Summary**

* vstack() combines arrays by stacking them on top of each other (increasing the number of rows).

* hstack() combines arrays by placing them side by side (increasing the number of columns).

Both functions are useful for manipulating array dimensions based on the desired structure of the resulting array.





In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In NumPy, the fliplr() and flipud() functions are used to flip arrays in different orientations. Here’s a detailed explanation of their differences and their effects on various array dimensions:

**fliplr()**

* Function: Flips an array left to right (horizontally).
* Usage: This function is specifically designed for 2D arrays, reversing the order of columns.

Example of fliplr()


In [8]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array left to right
flipped_lr = np.fliplr(array_2d)

print("Original Array:")
print(array_2d)
print("\nFlipped Left to Right:")
print(flipped_lr)


Original Array:
[[1 2 3]
 [4 5 6]]

Flipped Left to Right:
[[3 2 1]
 [6 5 4]]


**flipud()**

* Function: Flips an array up to down (vertically).
* Usage: This function can be applied to both 1D and 2D arrays, reversing the order of rows.

Example of flipud()


**Effects on Various Array Dimensions**

* 2D Arrays:

    * fliplr(): Reverses the order of columns. For example, if you have a matrix, it will reflect the matrix along the vertical axis.

    * flipud(): Reverses the order of rows. It reflects the matrix along the horizontal axis.

* 1D Arrays:

    * Both fliplr() and flipud() behave similarly for 1D arrays since there are no distinct rows and columns. They will simply reverse the order of the elements.
    
Example of 1D Array


In [9]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Flip left to right (same effect as up to down)
flipped_lr_1d = np.fliplr(array_1d.reshape(1, -1)).flatten()  # Reshaping to 2D for fliplr
flipped_ud_1d = np.flipud(array_1d)

print("\nOriginal 1D Array:")
print(array_1d)
print("\nFlipped Left to Right (1D):")
print(flipped_lr_1d)
print("\nFlipped Up to Down (1D):")
print(flipped_ud_1d)



Original 1D Array:
[1 2 3 4 5]

Flipped Left to Right (1D):
[5 4 3 2 1]

Flipped Up to Down (1D):
[5 4 3 2 1]


**Summary**

* fliplr(): Flips arrays horizontally (left to right). Primarily used for 2D arrays but can be applied to 1D arrays by reshaping.

* flipud(): Flips arrays vertically (up to down). Can be applied to both 1D and 2D arrays.

Understanding these functions is essential for effectively manipulating array data in different orientations in NumPy

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. This method is particularly useful when I want to divide a dataset into smaller chunks for processing or analysis.

Functionality
The basic syntax of array_split() is:



In [ ]:
numpy.array_split(ary, indices_or_sections, axis=0)


* ary: The input array you want to split.
* indices_or_sections: This can either be an integer (number of sections to create) or a 1D array of indices indicating where to split the array.

* axis: The axis along which to split the array. By default, this is set to 0 (the first axis).

**Handling Uneven Splits**

When using array_split(), if the array cannot be evenly divided by the number of sections specified, it will handle the remaining elements gracefully. Specifically:

1.**Uneven Splitting**: If the total number of elements is not divisible by the number of sections, some sub-arrays will contain more elements than others. NumPy ensures that the first few sub-arrays will have one more element than the others until all elements are accounted for.

2.Example


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 4)
print(result)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


Here, the first two sub-arrays have 2 elements each, while the last two sub-arrays have 1 element each, reflecting how the array was split unevenly.

**Conclusion**

The array_split() method is flexible and efficient for handling cases where the array cannot be evenly divided, making it a valuable tool in data manipulation and analysis within NumPy.





In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization and broadcasting are two powerful concepts in NumPy that enhance the efficiency of array operations and enable more intuitive coding. Here’s a breakdown of each concept:

**Vectorization**

Vectorization refers to the process of replacing explicit loops with array operations. In NumPy, operations are applied to entire arrays or large chunks of data at once, rather than iterating through individual elements. This is achieved by using optimized, low-level implementations in C and Fortran, which significantly speeds up computations.

**Benefits of Vectorization:**

* Performance: Vectorized operations are typically much faster than their loop-based counterparts because they reduce the overhead of Python's loop constructs.

* Conciseness: Code becomes more readable and concise, as vectorized operations can often replace several lines of code with a single expression.

Example:
Instead of using a loop to add two arrays element-wise

In [15]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.empty_like(a)

for i in range(len(a)):
    result[i] = a[i] + b[i]
resul = a + b #I can simply use

In [18]:
result

array([[11, 22, 33],
       [14, 25, 36]])

**Broadcasting**

Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. Instead of requiring the arrays to be of the same size, broadcasting automatically expands the smaller array across the larger array's dimensions in a compatible way.

**Rules of Broadcasting:**

* If the arrays have a different number of dimensions, the shape of the smaller array is padded with ones on the left side until both shapes match.

* The sizes of each dimension are compared. Two dimensions are compatible when:
     * They are equal, or
     *One of them is 1 (in which case it can be stretched to match the other dimension).

Example:
If you want to add a 1D array to a 2D array, NumPy will broadcast the 1D array across the rows of the 2D array:

In [16]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

result = a + b  # Broadcasting occurs here


In [17]:
result

array([[11, 22, 33],
       [14, 25, 36]])

**Contribution to Efficient Array Operations**

* Reduction of Complexity: Both vectorization and broadcasting allow I to write simpler code that abstracts away the details of iteration and shape manipulation, making the code easier to read and maintain.

* Performance Gains: These techniques leverage NumPy's underlying optimizations, leading to substantial performance improvements for array operations, especially on large datasets.

* Memory Efficiency: Broadcasting avoids the need to create large temporary arrays, as it works by virtually expanding the smaller array without allocating extra memory.

In summary,  
           vectorization and broadcasting are fundamental to NumPy’s design, allowing for efficient, concise, and high-performance array operations that are essential for scientific computing and data analysis

#**Practical Questions:**

In [ ]:
#1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

I can create a 3x3 NumPy array with random integers between 1 and 100 using the numpy.random.randint function. To interchange the rows and columns (transpose the array), I can use the .T attribute or the numpy.transpose function. Here's how I can do it:


In [19]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

# Print the transposed array
print("\nTransposed array:")
print(transposed_array)


Original array:
[[22 49 77]
 [95 88  9]
 [83 74 80]]

Transposed array:
[[22 95 83]
 [49 88 74]
 [77  9 80]]


**Explanation:**

* np.random.randint(1, 101, size=(3, 3)) generates a 3x3 array with random integers from 1 to 100.
* The .T attribute or np.transpose(array) is used to swap the rows and columns of the array.

When I run this code, you'll see the original array and its transposed version printed out.






In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

I can create a 1D NumPy array with 10 elements and reshape it into a 2x5 array and then into a 5x2 array using the numpy.reshape() method. Here’s how to do it:



In [20]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This creates an array with values from 0 to 9

# Print the original 1D array
print("Original 1D array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Print the 2x5 array
print("\nReshaped to 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the 5x2 array
print("\nReshaped to 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**Explanation:**

* np.arange(10) creates a 1D array with values from 0 to 9.
* reshape(2, 5) changes the shape of the array to 2 rows and 5 columns.
* reshape(5, 2) changes the shape to 5 rows and 2 columns.

When I run this code, it will display the original array, the reshaped 2x5 array, and the reshaped 5x2 array.

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

I can create a 4x4 NumPy array with random float values and then add a border of zeros around it using the numpy.pad function. Here’s how to do it

In [21]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Print the original 4x4 array
print("Original 4x4 array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 array with a border of zeros:")
print(array_with_border)


Original 4x4 array:
[[0.71188426 0.8559351  0.34866424 0.4736006 ]
 [0.29194694 0.23420815 0.33844987 0.89101027]
 [0.5203068  0.93988133 0.73356434 0.15957748]
 [0.14660639 0.58438533 0.09937709 0.60217103]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.71188426 0.8559351  0.34866424 0.4736006  0.        ]
 [0.         0.29194694 0.23420815 0.33844987 0.89101027 0.        ]
 [0.         0.5203068  0.93988133 0.73356434 0.15957748 0.        ]
 [0.         0.14660639 0.58438533 0.09937709 0.60217103 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Explanation:**

* np.random.rand(4, 4) generates a 4x4 array with random float values between 0 and 1.

* np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0) adds a border of zeros around the original array. The pad_width=1 specifies a border of one row/column of zeros on each side.

When I run this code, I'll see the original 4x4 array and the resulting 6x6 array with a border of zeros.





In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

I can create an array of integers from 10 to 60 with a step of 5 using the numpy.arange() function. Here’s how you can do it:



In [22]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


**Explanation:**

* np.arange(10, 61, 5) generates an array starting at 10, ending before 61, with a step of 5.

When I run this code, the output will be:



In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

I can create a NumPy array of strings and then apply different case transformations to each element using string methods. Here’s how you can do it:



In [23]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)    # Uppercase
lowercase_array = np.char.lower(array)    # Lowercase
titlecase_array = np.char.title(array)     # Title case
capitalize_array = np.char.capitalize(array)  # Capitalize

# Print the original and transformed arrays
print("Original array:")
print(array)

print("\nUppercase array:")
print(uppercase_array)

print("\nLowercase array:")
print(lowercase_array)

print("\nTitle case array:")
print(titlecase_array)

print("\nCapitalized array:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Title case array:
['Python' 'Numpy' 'Pandas']

Capitalized array:
['Python' 'Numpy' 'Pandas']


**Explanation:**

* np.char.upper(array) converts each string to uppercase.
* np.char.lower(array) converts each string to lowercase.
* np.char.title(array) converts each string to title case (first letter of each word capitalized).
* np.char.capitalize(array) capitalizes only the first letter of each string.

When I run this code, I'll see the original array along with the arrays transformed to different cases.





In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

I can create a NumPy array of words and then format each word to have spaces between each character using the following code:



In [24]:

import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print(spaced_words)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


Each word now has spaces between its characters!





In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Here's how I can create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [25]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


This code demonstrates how to perform the four basic arithmetic operations on 2D NumPy arrays.





In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

I can create a 5x5 identity matrix using NumPy and then extract its diagonal elements as follows:



In [26]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


This code creates a 5x5 identity matrix and extracts the diagonal elements, which will all be 1.





In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

I can generate a NumPy array of 100 random integers between 0 and 1000, and then find and display the prime numbers in that array using the following code:



In [27]:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check for prime numbers
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the results
print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [618 200 575 534 713 602 872  20 128 217 312  62 854 266 278 750 948 202
 268 596 368 381 530 528  68 105 277 860 733 789 106 382 899 662 396 503
 669 388 533 510 547 851  83 121 956 575  69  79 365 554 446 250 968 239
 802 587 219 271 531 829 533 651 820 125 544 333  17 959 747 684 952 112
   1 335 438 446 269 448 175 582 298 133 100  63 418 649 315 629 465 587
 405 836 134 965 604 574 821 741 866 703]
Prime Numbers:
 [277 733 503 547  83  79 239 587 271 829  17 269 587 821]


# **Output**
This code will print the array of random integers and the prime numbers found within that array. Each time I run the code, I'll get a different set of random integers.





In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

I can create a NumPy array representing daily temperatures for a month and then calculate the weekly averages as follows:

In [ ]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, using random temperatures between 20 and 35 degrees Celsius
daily_temperatures = np.random.randint(20, 36, size=30)

# Reshape the array to a 4x7 format (4 weeks, 7 days each)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)


# **Output**
This code will generate random daily temperatures and calculate the weekly averages. Each time you run it, I'll see a different set of temperatures and averages. The weekly averages will show the average temperature for each of the four weeks.



